### PR TITLE
xbuild/cargo: Use LLVM `libc++` std library on all platforms

### LINKED ISSUE #75: Should we pass `-stdlib=libc++` when building with `clang`?
Currently running into this on a custom CI image when building for Android: https://stackoverflow.com/questions/26333823/clang-doesnt-see-basic-headers

Seems the default is `-stdlib=libstdc++` which comes from `gcc-c++`, but our build should use the headers from `"--sysroot=$HOME/.cache/x/Android.ndk"`. The build starts working when using `-stdlib=libc++` which I think makes sense to add, since we "only do pure `clang` builds" anyway? Sorry, not very familiar with all the C/C++ header magic :sweat_smile:

EDIT: Made this change on my fork to be unblocked by this error: https://github.com/MarijnS95/xbuild/commit/bcc952494e6890c1fbbdf42584583b40106bcc4b

### PR DESCRIPTION
**Pull request by MarijnS95**
Fixes #75

Even though we pre-package and provide a sysroot for Android, iOS and MacOS - which are all based on LLVM's `libc++` stdlib, the compiler still tries to use the one from `gcc-c++` by default and fails otherwise for not even finding the standard headers (that are, again, provided in the prepackaged sysroot).

Telling the compiler to use this library through `-stdlib` resolves those header inclusion errors, without having to install `gcc-c++`.

### CODE REVIEW

File: xbuild/src/cargo/mod.rs [hunk 1]
```diff
@@ -194,6 +197,7 @@ impl CargoBuild {
         self.cfg_tool(Tool::Linker, "rust-lld");
         self.use_ld("lld-link");
         self.add_target_feature("+crt-static");
+        self.add_cxxflag("-stdlib=libc++");
```
Comment (MarijnS95) [inline xbuild/src/cargo/mod.rs:200]: @dvc94ch What do you think works on Windows?

**Comment by MarijnS95** [comment]
@dvc94ch As per "request" in https://github.com/cloudpeers/xbuild/issues/75 this covers all platforms, but I don't have the means to test/confirm it on Windows/iOS/MacOS - Android only - can you do that for me?

**Review by dvc94ch — APPROVED** [review]
